<?php

/**
 * @file
 * Tide Site Preview module.
 */

use Drupal\tide_site_preview\Hook\TideSitePreviewHooks;
use Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_site_preview_theme($existing, $type, $theme, $path) {
  return \Drupal::service(TideSitePreviewHooks::class)->theme($existing, $type, $theme, $path);
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_tide_site_preview_links(&$variables) {
  foreach ($variables['preview_links'] as &$preview_link) {
    $preview_link['link'] = !empty($preview_link['url']) ? Link::fromTextAndUrl($preview_link['url']->toString(), $preview_link['url']) : '';
  }
}
