<?php

/**
 * @file
 * Install file.
 */

use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\tide_publication\TidePublicationOperation;

/**
 * Implements hook_install().
 */
function tide_publication_install() {
  // Don't do anything else during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  TidePublicationOperation::addToWorkflows();
  TidePublicationOperation::addToScheduledTransitions();
  TidePublicationOperation::assignNecessaryPermissions(FALSE);
  TidePublicationOperation::addFieldsToSearchApi();

  // Creates vocabulary if doesn't exist.
  $vocabularies = Vocabulary::loadMultiple();
  if (!isset($vocabularies['organisation'])) {
    TidePublicationOperation::createVocabulary('organisation');
  }

}

/**
 * Implements hook_uninstall().
 */
function tide_publication_uninstall() {
  TidePublicationOperation::assignNecessaryPermissions(TRUE);
}
