<?php

/**
 * @file
 * Installation functions for Tide TFA.
 */

use Drupal\tide_tfa\TideTfaOperation;

/**
 * Setup TFA.
 */
function tide_tfa_install() {
  $tideTfaOperation = new TideTfaOperation();

  // Disabled site alert for TFA routes.
  $tideTfaOperation->disabledSiteAlertTfa();

  // Setup TFA settings.
  $tideTfaOperation->setupTfaSettings();

  // Setup TFA role permissions.
  $tideTfaOperation->setupTfaRolePermissions();
}
