<?php

/**
 * @file
 * Contains tide_tfa.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function tide_tfa_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // [SD-375] Bypass tfa during reset pass for all users.
  if ($form_id == 'tfa_settings_form') {
    if (isset($form['reset_pass_skip_enabled'])) {
      $form['reset_pass_skip_enabled']['#description'] = t('Allow TFA to be bypassed during password reset by the authenticated user.');
    }
  }
  if ($form_id == 'tfa_entry_form') {
    // [SD-294] Change the label of the 'Send' button.
    if (isset($form['actions']['send'])) {
      $form['actions']['send']['#value'] = t('Email me a verification code');
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function tide_tfa_menu_local_tasks_alter(&$data, $route_name, &$ref_root) {
  // Check if the tfa.overview tab exists in the current render array
  if (isset($data['tabs'][0]['tfa.overview'])) {
    $data['tabs'][0]['tfa.overview']['#link']['title'] = t('Multi-factor authentication');
  }

  // Check if the tfa.settings tab exists
  if (isset($data['tabs'][0]['tfa.settings'])) {
    $data['tabs'][0]['tfa.settings']['#link']['title'] = t('Multi-factor authentication settings');
  }
}
