<?php

/**
 * @file
 * Install file.
 */

use Drupal\Core\File\FileExists;
use Drupal\Core\File\FileSystemInterface;

/**
 * Implements hook_install().
 */
function tide_data_pipeline_install($is_syncing) {
  _tide_data_pipeline_install_csv_template_file();
}

/**
 * Installs the CSV template file.
 */
function _tide_data_pipeline_install_csv_template_file() {
  $file_directory = \Drupal::config('system.file')
    ->get('default_scheme') . '://csv_templates';
  \Drupal::service('file_system')
    ->prepareDirectory($file_directory, FileSystemInterface::CREATE_DIRECTORY);
  $module_path = \Drupal::service('extension.list.module')->getPath('tide_data_pipeline');
  $csv_source = $module_path . '/data/Generic_dataset_template.csv';
  \Drupal::service('file_system')
    ->copy($csv_source, $file_directory . '/Generic_dataset_template.csv', FileExists::Replace);
}
