version: '2'
services:
  cli:
    image: singledigital/bay-cli
    environment:
      - WEBROOT=build/docroot
      - COMPOSER=composer.build.json
    volumes:
      - .:/app
  php:
    image: singledigital/bay-php
    environment:
      - WEBROOT=build/docroot
    volumes:
      - .:/app
    depends_on:
      - cli
  nginx:
    image: singledigital/bay-nginx
    environment:
      - WEBROOT=build/docroot
    volumes:
      - .:/app
    networks:
      - default
    depends_on:
      - cli
    expose:
      - "8080"
  mariadb:
    image: singledigital/bay-mariadb
  selenium:
    image: selenium/standalone-chrome
