<?php

/**
 * @file
 * Tide external site link module functionality.
 */

use Drupal\user\Entity\Role;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_bundle_create().
 */
function tide_external_site_link_entity_bundle_create($entity_type_id, $bundle): void {
  if ($entity_type_id == 'node' && $bundle == 'external_site_link') {
    // Grant permissions to Approver and Editor.
    $roles = ['approver', 'editor'];

    $permissions = [
      'create profile content',
      'delete any profile content',
      'delete own profile content',
      'delete profile revisions',
      'edit any profile content',
      'edit own profile content',
      'revert profile revisions',
      'view profile revisions',
    ];

    foreach ($roles as $role_name) {
      $role = Role::load($role_name);
      if ($role) {
        foreach ($permissions as $permission) {
          $role->grantPermission($permission);
        }
        $role->save();
      }
    }
  }
}

/**
 * Implements hook_tide_site_preview_links_block_access_alter().
 */
function tide_external_site_link_tide_site_preview_links_block_access_alter(AccessResultInterface &$access, NodeInterface $node): void {
  if ($node->bundle() === 'external_site_link') {
    $access = AccessResult::forbidden();
  }
}

/**
 * Implements hook_tide_share_link_form_revision_overview_form_access_alter().
 */
function tide_external_site_link_tide_share_link_form_revision_overview_form_access_alter(AccessResultInterface &$access, NodeInterface $node): void {
  if ($node->bundle() === 'external_site_link') {
    $access = AccessResult::forbidden();
  }
}
