<?php

/**
 * @file
 * Tide external site link module functionality.
 */

use Drupal\user\Entity\Role;

/**
 * Implements hook_entity_bundle_create().
 */
function tide_external_site_link_entity_bundle_create($entity_type_id, $bundle) {
  if ($entity_type_id == 'node' && $bundle == 'external_site_link') {
    // Grant permissions on Test content type to Approver and Editor.
    $roles = ['approver', 'editor'];

    $permissions = [
      'create profile content',
      'delete any profile content',
      'delete own profile content',
      'delete profile revisions',
      'edit any profile content',
      'edit own profile content',
      'revert profile revisions',
      'view profile revisions',
    ];

    foreach ($roles as $role_name) {
      $role = Role::load($role_name);
      if ($role) {
        foreach ($permissions as $permission) {
          $role->grantPermission($permission);
        }
        $role->save();
      }
    }
  }
}
