<?php

/**
 * @file
 * Tide OAuth module.
 */

use Drupal\tide_oauth\Hook\TideOauthHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_tide_api_jsonapi_custom_query_parameters_alter().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_oauth_tide_api_jsonapi_custom_query_parameters_alter(&$custom_params) {
  return \Drupal::service(TideOauthHooks::class)->tideApiJsonapiCustomQueryParametersAlter($custom_params);
}

/**
 * Implements hook_theme().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_oauth_theme($existing, $type, $theme, $path) {
  return \Drupal::service(TideOauthHooks::class)->theme($existing, $type, $theme, $path);
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_oauth_theme_suggestions_consumer_alter(array &$suggestions, array $variables) {
  return \Drupal::service(TideOauthHooks::class)->themeSuggestionsConsumerAlter($suggestions, $variables);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Hide the Permissions section in Editorial Preview consumer.
 *
 * @see \Drupal\simple_oauth\Controller\Oauth2AuthorizeForm::buildForm()
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_oauth_form_simple_oauth_authorize_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return \Drupal::service(TideOauthHooks::class)->formSimpleOauthAuthorizeFormAlter($form, $form_state, $form_id);
}
