<?php

/**
 * @file
 * Tide Grant module install file..
 */

use Drupal\tide_grant\TideGrantOperation;

/**
 * Implements hook_install().
 */
function tide_grant_install() {
  // Don't do anything else during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
  $grantoperation = new TideGrantOperation();
  $grantoperation->addGrantAuthorUser();
  $grantoperation->assignNecessaryPermissions();
  $grantoperation->enableEditorialWorkflow();
  $grantoperation->addDefaultValueToContentCategory();
}

/**
 * Implements hook_uninstall().
 */
function tide_grant_uninstall() {
  // Remove the user we created.
  $users = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties(['name' => 'Grant Author']);
  if ($user = reset($users)) {
    $user->delete();
  }

  // Now cleanup the config.
  $config_factory = \Drupal::configFactory();
  // Remove the image styles that Linkit has installed.
  $config_factory->getEditable('user.role.grant_author')->delete();
}
