<?php

/**
 * @file
 * Tide Landing Page install.
 */

use Drupal\tide_landing_page\TideLandingPageOperation;

/**
 * Implements hook_install().
 */
function tide_landing_page_install() {

  // Don't do anything else during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  TideLandingPageOperation::addToWorkflows();
  TideLandingPageOperation::addToScheduledTransitions();
  TideLandingPageOperation::addWebformComponent();
  TideLandingPageOperation::assignNecessaryPermissions();
  TideLandingPageOperation::addFieldsToSearchApi();

}
