<?php

/**
 * @file
 * Install file for tide_ckeditor.
 */

use Drupal\filter\FilterFormatInterface;
use Drupal\user\Entity\Role;

/**
 * Install the tide_ckeditor module.
 */
function tide_ckeditor_install() {
  $role_ids = ['editor', 'approver', 'site_admin', 'contributor'];
  foreach ($role_ids as $role_id) {
    $role = Role::load($role_id);
    if ($role) {
      $role->grantPermission('use default embedded content button')->save();
    }
  }
}

/**
 * Enable the iframe permissions filter for existing text formats.
 */
function tide_ckeditor_update_10006() {
  $configuration = [
    'id' => 'tide_ckeditor_iframe_permissions',
    'provider' => 'tide_ckeditor',
    'status' => TRUE,
    'weight' => 101,
    'settings' => [],
  ];

  $storage = \Drupal::entityTypeManager()->getStorage('filter_format');
  foreach (['rich_text', 'admin_text', 'summary_text'] as $format_id) {
    $format = $storage->load($format_id);
    if ($format instanceof FilterFormatInterface) {
      $format
        ->setFilterConfig('tide_ckeditor_iframe_permissions', $configuration)
        ->save();
    }
  }
}
