<?php

/**
 * @file
 * Contains tide_site_alert.module.
 */

use Drupal\tide_site_alert\Hook\TideSiteAlertHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_site_alert_theme() {
  return \Drupal::service(TideSiteAlertHooks::class)->theme();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_site_alert_form_site_alert_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return \Drupal::service(TideSiteAlertHooks::class)->formSiteAlertFormAlter($form, $form_state, $form_id);
}

/**
 * The callback for the form alter above.
 */
function tide_site_alert_textfield_callback(&$form, FormStateInterface $form_state) {
  $selected = $form_state->getValue('suggested_labels');
  if ($selected != 'Other') {
    $form['label']['widget'][0]['value']['#value'] = $form_state->getValue('suggested_labels');
  }
  else {
    $form['label']['widget'][0]['value']['#value'] = '';
  }
  return $form['label'];
}
