<?php

/**
 * @file
 * Tide Profile module functionality.
 */

use Drupal\tide_profile\Hook\TideProfileHooks;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_entity_bundle_create().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_profile_entity_bundle_create($entity_type_id, $bundle) {
  return \Drupal::service(TideProfileHooks::class)->entityBundleCreate($entity_type_id, $bundle);
}

/**
 * Set dynamic allowed values for the year field.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function tide_profile_year_allowed_values(FieldStorageConfig $definition, ?ContentEntityInterface $entity = NULL, &$cacheable = TRUE) {
  $options = [];
  $years = range(date('Y'), 2001);
  // Add a custom alignment option for Article nodes.
  if ($entity->bundle() == 'profile') {
    foreach ($years as $year) {
      $options[$year] = $year;
    }
  }

  return $options;
}
