<?php

/**
 * @file
 * Install file.
 */

use Drupal\core\entity\Entity\EntityFormDisplay;
use Drupal\tide_site_restriction\TideSiteRestrictionOperation;

/**
 * Implements hook_install().
 */
function tide_site_restriction_install() {

  TideSiteRestrictionOperation::addSubSitesFilter();
  TideSiteRestrictionOperation::installWidgets();
  TideSiteRestrictionOperation::addNecessarySettings();
  TideSiteRestrictionOperation::updateHelpText();

}

/**
 * Update the help text on all field_node_site instances.
 */
function tide_site_restriction_update_10001() {
  TideSiteRestrictionOperation::updateHelpText();
}

/**
 * Update site fields widget for search_listing.
 */
function tide_site_restriction_update_10002() {
  if (!\Drupal::moduleHandler()->moduleExists('tide_search_listing')) {
    return t('tide_search_listing module is not enabled. Skipping update.');
  }

  $form_display = EntityFormDisplay::load('node.tide_search_listing.default');

  if ($form_display) {
    $form_display->setComponent('field_node_primary_site', [
      'type' => 'tide_site_restriction_field_widget',
      'weight' => 30,
      'region' => 'content',
      'settings' => [
        'enable_site_coupling' => FALSE,
      ],
      'third_party_settings' => [],
    ]);

    $form_display->setComponent('field_node_site', [
      'type' => 'tide_site_restriction_field_widget',
      'weight' => 40,
      'region' => 'content',
      'settings' => [
        'enable_site_coupling' => FALSE,
      ],
      'third_party_settings' => [],
    ]);

    $form_display->save();
  }
}
