<?php

/**
 * @file
 * Contains tide_ui_restriction.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_menu_links_discovered_alter().
 */
function tide_ui_restriction_menu_links_discovered_alter(&$links) {
  if (isset($links['system.modules_list'])) {
    unset($links['system.modules_list']);
  }

  if (isset($links['entity.user.collection'])) {
    if (\Drupal::moduleHandler()->moduleExists('admin_audit_trail')) {
      $links['tide_ui_restriction.admin_audit_trail.report_form'] = [
        'title' => t('Admin audit trail'),
        'description' => t('Get report about cud operation performed by the user on the website.'),
        'provider' => 'tide_ui_restriction',
        'route_name' => 'admin_audit_trail.report_form',
        'menu_name' => 'admin',
        'parent' => 'entity.user.collection',
        'weight' => 100,
      ];
    }
    if (\Drupal::moduleHandler()->moduleExists('event_log_track')) {
      $links['tide_ui_restriction.event_log_track.report_form'] = [
        'title' => t('Events Log Track'),
        'description' => t('Get report about cud operation performed by the user on the website.'),
        'provider' => 'tide_ui_restriction',
        'route_name' => 'event_log_track.report_form',
        'menu_name' => 'admin',
        'parent' => 'entity.user.collection',
        'weight' => 101,
      ];
    }
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function tide_ui_restriction_local_tasks_alter(&$local_tasks) {
  if (isset($local_tasks['system.modules_uninstall'])) {
    unset($local_tasks['system.modules_uninstall']);
  }
}

/**
 * Implements hook_admin_config_access_check_exclude().
 */
function tide_ui_restriction_admin_config_access_check_exclude($path) : bool {
  // Exclude URL Aliases and Redirects from _admin_config_access_check.
  $paths = [
    '/admin/config/search',
    '/admin/config/search/path',
    '/admin/config/search/redirect',
    '/admin/config/content/ckeditor-templates/template-selector/{editor}',
  ];
  if (in_array($path, $paths, TRUE)) {
    return TRUE;
  }

  $prefixes = [
    '/admin/config/search/path/',
    '/admin/config/search/redirect/',
  ];
  foreach ($prefixes as $prefix) {
    if (strpos($path, $prefix) === 0) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tide_ui_restriction_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_user = \Drupal::currentUser();
  if (!$current_user->hasRole('approver_plus')) {
    return;
  }

  // Hide higher roles.
  if (isset($form['account']['roles']) && is_array($form['account']['roles']['#options'])) {
    unset($form['account']['roles']['#options']['administrator']);
    unset($form['account']['roles']['#options']['site_admin']);
  }

  // Check if user is editing their own profile.
  // User can not change their own role and assign sites.
  $user_being_edited = $form_state->getFormObject()->getEntity();
  if ($current_user->id() == $user_being_edited->id()) {
    if (isset($form['account']['roles'])) {
      unset($form['account']['roles']);
    }
    if (isset($form['field_user_site'])) {
      unset($form['field_user_site']);
    }
  }
}
