<?php

/**
 * @file
 * Tide CMS Support.
 */

use Drupal\tide_cms_support\Hook\TideCmsSupportHooks;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_toolbar_alter().
 *
 * Attach css library.
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_cms_support_toolbar_alter(&$items) {
  return \Drupal::service(TideCmsSupportHooks::class)->toolbarAlter($items);
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_cms_support_block_view_tide_help_block_alter(array &$build, BlockPluginInterface $block) {
  return \Drupal::service(TideCmsSupportHooks::class)->blockViewTideHelpBlockAlter($build, $block);
}
