<?php

/**
 * @file
 * Tide CMS Support.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_toolbar_alter().
 *
 * Attach css library.
 */
function tide_cms_support_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'tide_cms_support/toolbar.icons';
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function tide_cms_support_block_view_tide_help_block_alter(array &$build, BlockPluginInterface $block) {
  // Assume that CMS users do not need or want to perform contextual actions on
  // the help block, so don't needlessly draw attention to it.
  unset($build['#contextual_links']);
}
