<?php

/**
 * @file
 * Tide Test module functionality.
 */

use Drupal\tide_test\Hook\TideTestHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_bundle_create().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_test_entity_bundle_create($entity_type_id, $bundle) {
  return \Drupal::service(TideTestHooks::class)->entityBundleCreate($entity_type_id, $bundle);
}

/**
 * Implements hook_modules_installed().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_test_modules_installed($modules) {
  return \Drupal::service(TideTestHooks::class)->modulesInstalled($modules);
}

/**
 * Implements hook_field_widget_form_alter().
 *
 * @todo Extract into a service.
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_test_field_widget_single_element_form_alter(&$element, FormStateInterface $form_state, $context) {
  return \Drupal::service(TideTestHooks::class)->fieldWidgetSingleElementFormAlter($element, $form_state, $context);
}

/**
 * Implements hook_config_ignore_settings_alter().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_test_config_ignore_settings_alter(array &$settings) {
  return \Drupal::service(TideTestHooks::class)->configIgnoreSettingsAlter($settings);
}
