<?php

/**
 * @file
 * Tide Site Theming module .
 */

use Drupal\tide_site_theming\Hook\TideSiteThemingHooks;

/**
 * Implements hook_field_group_form_process_alter().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_site_theming_field_group_form_process_alter(array &$element, &$group, &$complete_form) {
  return \Drupal::service(TideSiteThemingHooks::class)->fieldGroupFormProcessAlter($element, $group, $complete_form);
}
