<?php

/**
 * @file
 * Contains tide_inactive_users_management.module.
 */

use Drupal\user\UserInterface;
use Drupal\user\Entity\User;
use Drupal\block_inactive_users\InactiveUsersHandler;

/**
 * Implements hook_module_implements_alter().
 */
function tide_inactive_users_management_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'cron') {
    unset($implementations['block_inactive_users']);
  }
}

/**
 * Implements hook_user_login().
 */
function tide_inactive_users_management_user_login(UserInterface $account) {
  // Try to remove the key/value if user logged in.
  \Drupal::keyValue('tide_inactive_users_management')->delete($account->id());
}

/**
 * Helper function to send emails.
 */
function tide_inactive_users_management_sending_email(User $user, $sendmail = TRUE) {
  $logger = Drupal::service('logger.factory')
    ->get(InactiveUsersHandler::LOGGER_CHANNEL);
  $blockUserhandler = Drupal::service('block_inactive_users.deactivate_users');
  $config = \Drupal::configFactory()->get(InactiveUsersHandler::FORM_SETTINGS_CONFIG_OBJ_NAME);
  $logger->info($user->getAccountName() . ' has been notified.');
  $url = \Drupal::request()->getHost();
  if ($sendmail) {
    $blockUserhandler->mailUser($config
      ->get('block_inactive_users_from_email'),
      $user->getEmail(), $user->getAccountName(),
      $config
        ->get('block_inactive_users_email_subject'),
      $config
        ->get('block_inactive_users_email_content'),
      $url);
  }
  return $user;
}
