<?php

/**
 * @file
 * Tide News module.
 */

use Drupal\tide_news\Hook\TideNewsHooks;
use Drupal\Core\Form\FormStateInterface;
use Drupal\tide_core\TideCoreFormHelper;

/**
 * Implements hook_entity_bundle_create().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_news_entity_bundle_create($entity_type_id, $bundle) {
  return \Drupal::service(TideNewsHooks::class)->entityBundleCreate($entity_type_id, $bundle);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
#[\Drupal\Core\Hook\Attribute\LegacyHook]
function tide_news_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return \Drupal::service(TideNewsHooks::class)->formNodeFormAlter($form, $form_state, $form_id);
}

/**
 * Node form #process callback.
 *
 * @param array $form
 *   Form that is being processed.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param array $complete_form
 *   The complete form.
 *
 * @return array
 *   The processed form.
 */
function _tide_news_form_node_form_process(array $form, FormStateInterface $form_state, array $complete_form = []) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();
  TideCoreFormHelper::addHeaderStyleSelector($form, $form_state, $node, [
    'group' => 'group_customised_header',
    'fields' => [
      'field_graphical_image',
      'field_bottom_graphical_image',
    ],
    'after_build' => '_tide_event_form_node_form_after_build',
  ]);

  $form['field_node_department']['#group'] = 'group_author_detail';

  // At this stage, the form has not been fully built yet, so we need an
  // after_build callback to determine the actual state.
  $form['#after_build'][] = '_tide_news_form_node_form_after_build';
  return $form;
}

/**
 * Node form #after_build callback.
 *
 * @param array $form
 *   Form that is being processed.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 *
 * @return array
 *   The processed form.
 */
function _tide_news_form_node_form_after_build(array $form, FormStateInterface $form_state) {
  $form['field_node_department']['#group'] = 'group_author_detail';
  return $form;
}
