name: dorg_git_sync

on: push

jobs:
  dorg_git_sync:
    name: dorg_git_sync
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts:
            git.drupal.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCkFTXM7BUQUHlDkVmQV6qNkIeSIRBTNzlLn+T/APHa
            git.drupal.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEyYM2eEQJJLgBxDmCMHykxAkTLMryXJ2zHeQWMFaRCweHmivtuNRzvEfiir09IMwtC+1gP1Tu9tlkqXqtMrWl8=
            git.drupal.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbjTZ+rsrZ82kHqPBFfRxP/JJJWrpAaOGGS5Qj6ewK3gQt/ENa47e/rqAjvm8aSvm0GAhjbMmgKQA95USTRqT/VmNmX9NsGzvG1FV9PZ2q6ejoeAkT6PAOF+ZNrG1nNx4ly9h3mYocNgEx6GhqQHznzwXHqK82ZEtXNBVjd+i+sCbz54udQTUZH+KV/yeqYDKsYYA9o+R8ULPTF89bqCaTEy6NyP4d+mv+nqt8ztSWLph8mjol6Cr/LpNtM2Xijr8KmeJ9cEjOW2Tj3v2pyAHhBtLRtL8UgQGRUcOgMgj8fZHAFOhK36n9Esv+i7sFfALy1v0DdLObk8ixWc5eZF1x
          if_key_exists: fail
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure Drupal.org remote
        run: |
          git remote add dorg git@git.drupal.org:project/tide_core.git
      - name: Push the current branch to the Drupal.org remote
        run: |
          git push dorg HEAD
          git push dorg --tags